### ISSUE TITLE
Internal server error in releaseTree

### ISSUE THREAD

**Issue by Cactucs** [contember/contember#101]
```
api_1      | TypeError: Cannot read property 'name' of undefined
api_1      |     at /src/node_modules/@contember/engine-content-api/dist/src/bridges/system/ContentEventApplier.js:147:99
api_1      |     at Array.map (<anonymous>)
api_1      |     at ContentEventApplier.applyEntityCreate (/src/node_modules/@contember/engine-content-api/dist/src/bridges/system/ContentEventApplier.js:147:57)
api_1      |     at ContentEventApplier.applyEntityEvent (/src/node_modules/@contember/engine-content-api/dist/src/bridges/system/ContentEventApplier.js:135:35)
api_1      |     at ContentEventApplier.applyEvent (/src/node_modules/@contember/engine-content-api/dist/src/bridges/system/ContentEventApplier.js:117:31)
api_1      |     at ContentEventApplier.apply (/src/node_modules/@contember/engine-content-api/dist/src/bridges/system/ContentEventApplier.js:103:39)
api_1      |     at runMicrotasks (<anonymous>)
api_1      |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
api_1      |     at async ReleaseExecutor.execute (/src/node_modules/@contember/engine-system-api/dist/src/model/events/ReleaseExecutor.js:36:24)
api_1      |     at async /src/node_modules/@contember/engine-system-api/dist/src/resolvers/mutation/ReleaseTreeMutationResolver.js:42:28
```

https://github.com/skaut/znalostnibaze-api/pull/70

**Comment by matej21** [comment]
bug in event migrations fixed in 7df474c74c1d23c94ea0e2cb0429bef8894491e7, however existing defective events will still fail. you have to fix existing events by yourself
