### ISSUE TITLE
Internal server error when using hasMany relation

### ISSUE THREAD

**Issue by VojtaStanek** [contember/contember#178]
Request returns "Internal server error". 

Request:
```json
{"query":"query {\n\test_212628574: getLabel(by: {id: \"7f44883b-baf2-4e3d-a7d1-291d7a779c38\"}) {\n\t\tid\n\t\tname\n\t\titems_1342132415: items {\n\t\t\tid\n\t\t}\n\t}\n}"}
```

Response:
```json
{"errors":[{"message":"Internal server error"}],"data":{"est_212628574":null},"extensions":{"dbQueries":[{"sql":"select \"name\", \"migration\", \"checksum\", \"executed_at\"  from \"system\".\"schema_migration\"  where \"version\" > ?  order by \"version\" asc","bindings":["2021-07-30-132644"],"elapsed":5856,"meta":{"module":"system"},"rowCount":0,"path":[]},{"sql":"select \"root_\".\"id\" as \"root_id\", \"root_\".\"name\" as \"root_name\", \"root_\".\"id\" as \"root_id\"  from \"stage_live\".\"label\" as \"root_\"  where \"root_\".\"id\" = ?","bindings":["7f44883b-baf2-4e3d-a7d1-291d7a779c38"],"elapsed":5148,"meta":{"module":"content","path":["est_212628574"]},"rowCount":1,"path":["est_212628574"]},{"sql":"select \"junction_\".\"label_id\", \"junction_\".\"item_id\"  from \"stage_live\".\"item_labels\" as \"junction_\"  where \"junction_\".\"label_id\" in (?)","bindings":["7f44883b-baf2-4e3d-a7d1-291d7a779c38"],"elapsed":1837,"meta":{"module":"content"},"rowCount":0,"path":[]}]}}

```

Schema:
```ts
export class Label {
	name = def.stringColumn().notNull()
	archived = def.boolColumn().notNull().default(false)
	items = def.manyHasManyInverse(Item, 'labels')
}

export const ItemSource = def.createEnum('news', 'gov')

export class Item {
	source = def.enumColumn(ItemSource).notNull()
	nodeId = def.column(ColumnType.Uuid).notNull()
	labels = def.manyHasMany(Label, 'items')
}
```

Logs:
```
api_1      | Error: Cannot return null for non-nullable field Label.items.
api_1      |     at completeValue (/src/node_modules/graphql/execution/execute.js:561:13)
api_1      |     at resolveField (/src/node_modules/graphql/execution/execute.js:474:19)
api_1      |     at executeFields (/src/node_modules/graphql/execution/execute.js:294:18)
api_1      |     at collectAndExecuteSubfields (/src/node_modules/graphql/execution/execute.js:749:10)
api_1      |     at completeObjectValue (/src/node_modules/graphql/execution/execute.js:739:10)
api_1      |     at completeValue (/src/node_modules/graphql/execution/execute.js:592:12)
api_1      |     at /src/node_modules/graphql/execution/execute.js:471:16
api_1      |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
api_1      |     at async Promise.all (index 0)
```

Id in the request exists. Without `items {id}` the query returns normally.

**Comment by matej21** [comment]
fixed: a192259da233e8591c84f26225c610db6d60087e
