### ISSUE TITLE
`instance:up` fails in new workspace

### ISSUE THREAD

**Issue by michalhosna** [contember/contember#19]
When I create workspace according to getting started, `instance:up` fails
```
❯ npx contember instance:up
No stopped containers
Creating network "default_default" with the default driver
Creating default_s3_1      ... done
Creating default_db_1      ... done
Creating default_mailhog_1 ... done
Creating default_api_1     ... done
Creating default_adminer_1 ... done
It seems that this is first run of this instance. Will try to execute a setup.
If that is not true, please fill your login token to a contember.instance.local.yaml
✔ Superadmin email … example@example.com
✔ Superadmin password … ******
Error: Authorization failure: disabled: {"response":{"errors":[{"message":"Authorization failure: disabled","code":401}],"status":401},"request":{"query":"mutation($email: String!, $password: String!) {\n  setup(superadmin: {email: $email, password: $password}) {\n    ok\n    result {\n      loginKey {\n        token\n      }\n    }\n  }\n}","variables":{"email":"example@example.com","password":"123456"}}}
    at GraphQLClient.<anonymous> (/usr/local/lib/node_modules/@contember/cli/node_modules/graphql-request/src/index.ts:72:13)
    at step (/usr/local/lib/node_modules/@contember/cli/node_modules/graphql-request/dist/src/index.js:40:23)
    at Object.next (/usr/local/lib/node_modules/@contember/cli/node_modules/graphql-request/dist/src/index.js:21:53)
    at fulfilled (/usr/local/lib/node_modules/@contember/cli/node_modules/graphql-request/dist/src/index.js:12:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  response: { errors: [ [Object] ], status: 401 },
  request: {
    query: 'mutation($email: String!, $password: String!) {\n' +
      '  setup(superadmin: {email: $email, password: $password}) {\n' +
      '    ok\n' +
      '    result {\n' +
      '      loginKey {\n' +
      '        token\n' +
      '      }\n' +
      '    }\n' +
      '  }\n' +
      '}',
    variables: { email: 'example@example.com', password: '123456' }
  }
}
 
```
[![asciicast](https://asciinema.org/a/EZKewp6LkrwOdbJ9sMpGZkFrm.svg)](https://asciinema.org/a/EZKewp6LkrwOdbJ9sMpGZkFrm)

Also, hiding password during input and then showing it in the error message doesn't seem like a great idea.

**Comment by michalhosna** [comment]
Figured it out. 

The problem is that, even if I do `instance:down`, docker volume `default_pgsql-data` still exists and holds data. If I try to run another workspace with instance name default, it fails like this ☝️.

The error message is not helpful at all.
Also, is there any way I can run multiple workspaces with default instance? Not even simultaneously, but switching between them without having to drop db data?

---
Sidenote:
I think, that contember should not touch `docker-compose` commands at all. Generate docker-compose.yaml, and let the developer handle the rest, hiding it doesn't help anything. 

And generating several `default_*` containers and volumes is really awful behaviour.
