### ISSUE TITLE
AssertionError when creating workspace

### ISSUE THREAD

**Issue by Rikkard29** [contember/contember#72]
When running npx contember workspace:create test I get the following error.

`
AssertionError [ERR_ASSERTION]: 'undefined' == 'string'
    at npa (C:\Users\Michael\AppData\Roaming\npm\node_modules\@contember\cli\node_modules\get-npm-registry-package\node_modules\npm-package-arg\npa.js:41:10)
    at module.exports (C:\Users\Michael\AppData\Roaming\npm\node_modules\@contember\cli\node_modules\get-npm-registry-package\dist\index.js:33:42)
    at Object.default (C:\Users\Michael\AppData\Roaming\npm\node_modules\@contember\cli\node_modules\get-package-json-from-registry\dist\index.js:31:12)
    at Object.exports.downloadPackage (C:\Users\Michael\AppData\Roaming\npm\node_modules\@contember\cli\src\utils\npm.ts:14:34)
    at Object.exports.installTemplate (C:\Users\Michael\AppData\Roaming\npm\node_modules\@contember\cli\src\utils\template.ts:25:9)
    at Object.exports.createWorkspace (C:\Users\Michael\AppData\Roaming\npm\node_modules\@contember\cli\src\utils\workspace.ts:24:2)
    at WorkspaceCreateCommand.execute (C:\Users\Michael\AppData\Roaming\npm\node_modules\@contember\cli\src\commands\workspace\WorkspaceCreateCommand.ts:27:3)
    at WorkspaceCreateCommand.run (C:\Users\Michael\AppData\Roaming\npm\node_modules\@contember\cli\src\cli\Command.ts:24:18)
    at Application.run (C:\Users\Michael\AppData\Roaming\npm\node_modules\@contember\cli\src\cli\Application.ts:47:19)
    at C:\Users\Michael\AppData\Roaming\npm\node_modules\@contember\cli\src\run.ts:72:2 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 'undefined',
  expected: 'string',
  operator: '=='
}

`

**Comment by FilipChalupa** [comment]
This works for me in `wsl2` under an empty directory: `npx @contember/cli workspace:create test`

![image](https://user-images.githubusercontent.com/1045362/89733595-b9f36480-da56-11ea-9b87-64fa41e3c187.png)

**Comment by Rikkard29** [comment]
I have tried it in multiple empty directories on Windows and I am still getting the same error :/

**Comment by JirkaVebr** [comment]
@Rikkard29 I believe @FilipChalupa was pointing out the use of `@contember/cli` as opposed to just `contember` which you used originally. Have you tried that?

As for the `contember` package, thanks for bringing this to our attention! We do own it but have yet to publish anything meaningful there. Hopefully, we will be able to fix that soon.

**Comment by Rikkard29** [comment]
Yes I have tried replacing contember with @contember/cli. The result is same.

**Comment by matej21** [comment]
thanks for a report
fixed in 8a031c3bbda7286b70b8f67da3a1094128b18d09 
I will release a new version soon, hopefully tomorrow. But still I cannot guarantee Contember works properly on windows, we are using it only on linux and in WSL

**Comment by JirkaVebr** [comment]
@Rikkard29 I would just like to add that while we haven't yet been able to test everything thoroughly on Windows, it is absolutely our goal to support this use case too, and it is issues like yours that help us get there. Thank you for trying out Contember and if you stumble upon any other problems, please do report them as well! :slightly_smiling_face:

**Comment by Rikkard29** [comment]
@JirkaVebr Thank you for clarification. I really like the technologies you used to create this CMS. Supporting windows would be a great improvement. Keep up the good work.
